spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-lakers-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-lakers-test