spring:
  profiles:
    active: dev

---
server:
  port: 3001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://MicroServiceCloud-Eureka-E1:7001/eureka

---
server:
  port: 3002

spring:
  profiles: test
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://MicroServiceCloud-Eureka-E1:7001/eureka
